# Set folder to clover (must be the same on travis)
coverage_clover: coverage/xml/clover.xml
# Same folder here
json_path: coverage/xml/coveralls-upload.json
# Don't touch that
service_name: travis-ci