services:
  composernormalize:
    version:        latest
  phpcs:
    version:        latest
    config_path:    ~
    paths:          ['src']
    composer:       false
  phpcsfixer:
    version:        latest
    config_path:    ~
